exports.seed = function(knex, Promise) {
  return knex('company_table').del()
    .then(function() {
      return knex('company_table').insert([{
          company_id: 'sarahco',
          company_name: 'Sarahs company',
          company_email: "sarah@sarahco.com",
          company_phone: "5555555555",
          company_content_creator: 'test company content creator',
          company_brand_id: "test_brand_id",
          company_primary_goal: "Get good at being Sarahco",
          company_style_guide: "test style guide",
          company_website: 'Sarahco.com',
          google_search_goals: 'be the only search result for any sarah query',
          google_business_profile: 'sarah.google.com',
          instagram_username: 'sarah@instagram',
          instagram_goals: 'money',
          instagram_bio: "we're a mom and pop shop",
          facebook_page_url: 'sarah.facebook.com',
          facebook_goals: 'become ceo of all Sarahs',
          twitter_username: '@sarah_co',
          twitter_goals: 'become Sarah number one',
          linkedin_profile_url: 'sarahco@linkedin',
          linkedin_goals: 'Get linked up',
          google_plus_profile_url: 'K??',
          google_plus_goals: 'become popular',
          youtube_url: 'sarah.youtube.com',
          vimeo_url: 'sarah@vimeo.com',
          youtube_vimeo_goals: 'become famous',
          pinterest_profile: 'sarah@pinterest.com',
          pinterest_goals: 'become number one sarah in my zone',
          yelp_business_profile: 'sarah@yelp.com',
          yelp_goals: '10 star rating',
          better_business_bureau_profile: 'sarah@bbb.com',
          better_business_bureau_goals: '100%',
          insta_goal1: 'learn the secrets',
          insta_goal2: 'of winning friends',
          insta_goal3: 'and influencing people',
          cloudbased_storage_locale: 'www.yermomsbasement.com',
        },
        {
          company_id: 'joeco',
          company_name: 'JoeCo',
          company_email: "joe@joeco.com",
          company_phone: "5555555555",
          company_content_creator: 'test company content creator',
          company_brand_id: "test_brand_id",
          company_primary_goal: "Make joe number 1!",
          company_style_guide: "test style guide",
          company_website: 'joeJoes.com',
          google_search_goals: 'be the only search result for any query',
          google_business_profile: 'joe.google.com',
          instagram_username: 'joe@instagram',
          instagram_goals: 'get Joe seen',
          instagram_bio: "Joe for bros.",
          facebook_page_url: 'joe.facebook.com',
          facebook_goals: 'become top Joe',
          twitter_username: '@joeCo',
          twitter_goals: 'become number one',
          linkedin_profile_url: 'test@linkedin',
          linkedin_goals: 'joes info',
          google_plus_profile_url: 'K??',
          google_plus_goals: 'become popular Joe',
          youtube_url: 'Joe.youtube.com',
          vimeo_url: 'Joe@vimeo.com',
          youtube_vimeo_goals: 'become Joe',
          pinterest_profile: 'Joe@pinterest.com',
          pinterest_goals: 'become Joenumber one',
          yelp_business_profile: 'Joe@yelp.com',
          yelp_goals: '10 star rating',
          better_business_bureau_profile: 'Joe@bbb.com',
          better_business_bureau_goals: '100%',
          insta_goal1: 'learn the secrets',
          insta_goal2: 'of winning friends',
          insta_goal3: 'and influencing people',
          cloudbased_storage_locale: 'www.yermomsbasement.com',
        },
        {
          company_id: 'hiroshico',
          company_name: 'HiroshiCo',
          company_email: "hiroshi@joeco.com",
          company_phone: "5555555555",
          company_content_creator: 'test company content creator',
          company_brand_id: "test_brand_id",
          company_primary_goal: "Make Hiroshi number 1!",
          company_style_guide: "test style guide",
          company_website: 'Hiroshi.com',
          google_search_goals: 'be the only search result for any query',
          google_business_profile: 'Hiroshi.google.com',
          instagram_username: 'Hiroshi@instagram',
          instagram_goals: 'get Hiroshi seen',
          instagram_bio: "Hiroshi for bros.",
          facebook_page_url: 'Hiroshi.facebook.com',
          facebook_goals: 'become top Hiroshi',
          twitter_username: '@hiroshiCo',
          twitter_goals: 'become number one',
          linkedin_profile_url: 'Hiroshi@linkedin',
          linkedin_goals: 'Hiroshi info',
          google_plus_profile_url: 'K??',
          google_plus_goals: 'become popular Hiroshi',
          youtube_url: 'Hiroshi.youtube.com',
          vimeo_url: 'Hiroshi@vimeo.com',
          youtube_vimeo_goals: 'become Hiroshi',
          pinterest_profile: 'Hiroshi@pinterest.com',
          pinterest_goals: 'become Joenumber Hiroshi',
          yelp_business_profile: 'Joe@yelp.com',
          yelp_goals: '10 star rating',
          better_business_bureau_profile: 'hiroshi@bbb.com',
          better_business_bureau_goals: '100%',
          insta_goal1: 'learn the secrets',
          insta_goal2: 'of winning friends',
          insta_goal3: 'and influencing people',
          cloudbased_storage_locale: 'www.yermomsbasement.com',
        },
        {
          company_id: 'francoisco',
          company_name: 'francoisCo',
          company_email: "francois@joeco.com",
          company_phone: "5555555555",
          company_content_creator: 'francois company content creator',
          company_brand_id: "test_brand_id",
          company_primary_goal: "Make francois number 1!",
          company_style_guide: "francois style guide",
          company_website: 'francois.com',
          google_search_goals: 'be the onfrancoisly search result for any query',
          google_business_profile: 'francois.google.com',
          instagram_username: 'francois@instagram',
          instagram_goals: 'get francois seen',
          instagram_bio: "francois for bros.",
          facebook_page_url: 'francois.facebook.com',
          facebook_goals: 'become top francois',
          twitter_username: '@francois',
          twitter_goals: 'become number one',
          linkedin_profile_url: 'francois@linkedin',
          linkedin_goals: 'francois info',
          google_plus_profile_url: 'K??',
          google_plus_goals: 'become popular francois',
          youtube_url: 'francois.youtube.com',
          vimeo_url: 'francois@vimeo.com',
          youtube_vimeo_goals: 'become francois',
          pinterest_profile: 'francois@pinterest.com',
          pinterest_goals: 'become francois Hiroshi',
          yelp_business_profile: 'francois@yelp.com',
          yelp_goals: '10 star rating',
          better_business_bureau_profile: 'francois@bbb.com',
          better_business_bureau_goals: '100%',
          insta_goal1: 'learn the secrets',
          insta_goal2: 'of winning friends',
          insta_goal3: 'and influencing people',
          cloudbased_storage_locale: 'www.francois.com',
        }
      ]);
    });
};
